services:
  temperature-data-explorer:
    image: ghcr.io/lilli30101/temperature_data_explorer:latest
    ports:
      - "8000:8000"
    environment:
      CLIMATE_REQUEST_TIMEOUT_SECONDS: "20"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
